### ISSUE TITLE
HDCP Support for MiSTerCast

### ISSUE THREAD

**Issue by KingKannibal** [iequalshane/MiSTerCast#10]
# HDCP Support for MiSTerCast

## Description

HDCP (High-bandwidth Digital Content Protection) is a form of digital copy protection technology used to prevent unauthorized copying of audio and video content transmitted over digital interfaces like HDMI.

## Use Case

HDCP support for MiSTerCast would be necessary when attempting to stream content from services like Amazon Prime through a web browser like Firefox. Without HDCP support, MiSTerCast will produce a black screen on Groovy due to HDCP encryption.

## Screenshot

This is the preview displayed by MiSTerCast and what is visible on Groovy.
![MiSTerCast_8dBt40qW3Q](https://github.com/iequalshane/MiSTerCast/assets/69727262/d9770e6f-3d03-498b-90ca-1dee082314ae)

**Comment by iequalshane** [comment]
This would not be possible and maybe not legal to circumvent the HDCP protection in the software. However, a workaround is to disable graphics acceleration in your browser settings and then HDCP will be disabled.
