### ISSUE TITLE
Loosing sync after "Start Stream"

### ISSUE THREAD

**Issue by sonic74** [iequalshane/MiSTerCast#2]
I can see the Groovy screensaver on my 15 KHz monitor connected via
https://ultimatemister.com/product/mister-hdmi-scart-direct-video/
(and another one) but as soon as I click "Start Stream" they loose sync.

**Comment by iequalshane** [comment]
Are both the MiSTer and PC connected to the network through ethernet? WiFi is not supported.

**Comment by sonic74** [comment]
Yes.

**Comment by iequalshane** [comment]
Were you able to get Groovy_Mame to work fine with the core? Are you using a modeline that's compatible with your CRT? I supplied NTSC modelines in the modelines.dat file but if you have a PAL TV you can add PAL modelines. Also, did you download the hotfix version of the release?

**Comment by sonic74** [comment]
Groovy_Mame works fine.
I used both the 256/320x240 default modelines.
The monitors can do both PAL & NTSC.
I didn't see any hotfix version at https://github.com/iequalshane/MiSTerCast/releases

**Comment by iequalshane** [comment]
MiSTerCast_1_00_hotfix1.zip is the hotfix version on that link.

**Comment by sonic74** [comment]
aah, didn't see that, thanks, it wörks 😀

**Comment by iequalshane** [comment]
Awesome!
